name: Test Runner

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Lint And Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Install dependencies & run coverage
        # Install coverage CLI analyzer
        # run: npm install -D c8
        # # Run c8 to get a detailed per-file report
        # run: npx c8 --reporter=text --reporter=html npx jest
        # # Open HTML report to visually inspect uncovered branches
        # run: open coverage/index.html
        run: | 
          npm install -D c8 
          npx c8 --reporter=text --reporter=html npx jest
          
        # Upload coverage HTML report as an artifact to view in GitHub UI
      - name: Upload Coverage HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/

      - name: Check Complexity of Existing Tests
        # Install tools
        # npm install -D eslint-plugin-jest complexity-report
        # Check cyclomatic complexity of your test files
        # npx cr --format plain --output complexity-report.txt ./src/**/*.test.ts
        run: | 
          npm install -D eslint-plugin-jest complexity-report
          npx cr --format plain --output complexity-report.txt ./src/**/*.test.ts

        

